name: dev
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - sandbox
jobs:
  ci:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
