# This is a basic workflow to help you get started with Actions

name: Title Check

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events of some types but only for the master branch
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check_pr_title:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check PR title
        if: ${{ !contains(github.event.pull_request.title, '[BTW-]') }}
        run: |
          echo "PR title does not contain the jira ticket reference"
          exit 1
  ci:
    if: "!contains(github.event.head_commit.message, '[skip ci]' && github.event.pull_request.action != 'edited'"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

